### ISSUE TITLE
Fencing

### ISSUE THREAD

**Issue by YetiActual** [richardwilkes/gcs_library#121]
why is fencing missing from the skills list?

**Comment by richardwilkes** [comment]
What "fencing" skill are you referring to? There isn't one in the Basic Set that I'm aware of, although I suppose some other book could have such a thing. Instead, there are a collection of skills, collectively referred to as "fencing skills" or "fencing weapons", depending on just where it is written: Main-Gauche, Rapier, Saber, or Smallsword.

Even if there is supposed to be such a skill and it was missing, the answer would be "because no one bothered to enter the info in and contribute it to the project". I generally do not do data entry -- I spend far too much of my time writing the code as it is.

**Comment by YetiActual** [comment]
Fencing is in the combat weapon skills on page 50 of the 3rd edition.  You use your fencing skill to wield a rapier, smallsword or saber.  Your parry is 2/3 your fencing skill.

**Comment by richardwilkes** [comment]
Ah... GCS doesn't directly support 3rd Edition, as the rules are different enough that they can't be done without significant data changes. Fencing does not exist as a standalone skill in 4th Edition as far as I can tell.

**Comment by YetiActual** [comment]
That explains it.  My groups just has not felt the need to look at 4th
edition yet.  Your work looks great and thanks for the quick response.
Maybe we can still find a way to use it to generate characters.  I also see
that the characters from GCS are importable into Fantasy Grounds, which I
am considering trying, due to covid really cutting into gaming.

Live Long and Prosper
