### ISSUE TITLE
Monowire Switchblade - Damage Calculations

### ISSUE THREAD

**Issue by LawfulNoodle** [richardwilkes/gcs_library#79]
When using the Monowire Switchblade as a weapon it pulls the sw damage value from the character but then does something weird to get the final calculation.
It should be:
sw+1d+R(10) cut, which for a character with sw=1d+1, is 2d+1+R(10) cut. 
It populates onto the sheet as:
1d+2d+R(10) cut or 3d+R(10) cut.

I don't know if this is some interaction I'm missing or if does some weird math interaction to get this.

**Comment by richardwilkes** [comment]
The notation where additional dice of damage are added isn't currently supported -- the code that tries to reconcile things doesn't blow up, but clearly needs to be updated for such things. This is the first I've seen of that type of damage, not that I've looked very hard. Is this a one-off, or are there a significant number of these in the official rules that I just missed?

**Comment by LawfulNoodle** [comment]
The only weapons, as far as I can tell, that have additional die are the Monowire Switchblade, Monowire Whip, and the Stasis Switchblade. So its just the three instances.
 I only stumbled upon it because I was adding in a custom weapon. Even if it didn't add the extra dice into one term and just listed out all of the values [like 1d+1+1d+R(10) cut], that would at least give people the right number of dice.

**Comment by richardwilkes** [comment]
Took a quick look at this today. One workaround for now is to ensure the dice notation comes first, so that it doesn't get confused by additions. For example, the monowire switchblade is listed as "sw+1d+R(10)". Instead, list it as "1d+sw+R(10)". When listed the first way, the parser mistakenly updates the "sw+1" part with the character's swing info, rather than just the "sw" part. This is because normally that's the right thing to do (i.e. taking "sw+1", turning it into "2d+1+1" (for 15 ST), then resolving that to "2d+2". Unfortunately, when the remainder of the string ("d+R(10)") is then re-added, it becomes "2d+2d+R(10)". If you place it as in the second example, then the parser properly extracts just the "sw", turns it into "2d+1", then re-adds the prefix ("1d+") and suffix("+R(10"), resulting in "1d+2d+1R(10)". Still not ideal, but doesn't inadvertently add extra dice.

**Comment by richardwilkes** [comment]
Updated the data files for the entries you noted in commit 3a5f4a1
