### ISSUE TITLE
Advantages, Basic Set - Enhanced Defences don't have levels

### ISSUE THREAD

**Issue by Irdes** [richardwilkes/gcs_library#91]
Enhanced Block and Enhanced Dodge don't have levels at all, while Enhanced Parries of all kinds do, but don't have the 'Per Level' bonus set in, so always add +1 regardless of level.

**Comment by richardwilkes** [comment]
According to the text on B51, none of the enhanced defenses have levels, at least not with GM intervention. I assume you filed this because whoever made the ones for Parry in the library marked them as having levels, but then didn't actually do anything with that. I'll fix it so that they don't think they have levels, which is the standard definition for them from B51.
